"""Imports ONLY `enum` — nothing else (see src/calls/constants.py's docstring for why)."""

from enum import StrEnum


class ActionCode(StrEnum):
    """All 21 codes from spec §25, verbatim. Cross-checked 1:1 against
    tests/fixtures/spec_action_codes.txt by tests/unit/test_disposition_action_enums.py."""

    CALLBACK_SCHEDULED = "CALLBACK_SCHEDULED"
    CLAIM_DELAY_ESCALATION = "CLAIM_DELAY_ESCALATION"
    DOCUMENT_STATUS_DISPUTE = "DOCUMENT_STATUS_DISPUTE"
    DOCUMENT_SUBMISSION_LINK_REQUEST = "DOCUMENT_SUBMISSION_LINK_REQUEST"
    CLAIM_REVIEW_REQUEST = "CLAIM_REVIEW_REQUEST"
    COMPLAINT_CREATED = "COMPLAINT_CREATED"
    HUMAN_CALLBACK_CREATED = "HUMAN_CALLBACK_CREATED"
    CUSTOMER_CONTACT_DETAILS_REVIEW = "CUSTOMER_CONTACT_DETAILS_REVIEW"
    GARAGE_CONTACT_REQUEST = "GARAGE_CONTACT_REQUEST"
    CLAIMS_TEAM_QUERY = "CLAIMS_TEAM_QUERY"
    SPECIAL_CIRCUMSTANCE_REVIEW = "SPECIAL_CIRCUMSTANCE_REVIEW"
    COMMUNICATION_SUPPRESSION = "COMMUNICATION_SUPPRESSION"
    DSAR_REQUEST_CREATED = "DSAR_REQUEST_CREATED"
    ACCESSIBLE_CHANNEL_REQUEST = "ACCESSIBLE_CHANNEL_REQUEST"
    SECURITY_REVIEW_REQUEST = "SECURITY_REVIEW_REQUEST"
    VULNERABLE_CUSTOMER_SUPPORT_REQUEST = "VULNERABLE_CUSTOMER_SUPPORT_REQUEST"
    FRAUD_SIU_REVIEW_REQUEST = "FRAUD_SIU_REVIEW_REQUEST"
    EVIDENCE_PRESERVATION_REQUEST = "EVIDENCE_PRESERVATION_REQUEST"
    TECHNICAL_RECOVERY_FOLLOWUP = "TECHNICAL_RECOVERY_FOLLOWUP"
    BACKEND_DATA_VERIFICATION_REQUEST = "BACKEND_DATA_VERIFICATION_REQUEST"
    COMPLAINT_SLA_ESCALATION = "COMPLAINT_SLA_ESCALATION"
