"""Imports ONLY `enum` — nothing else. This module runs inside the Temporal workflow
sandbox (see src/calls/workflows.py and tests/integration/test_phase0_e2e.py); pulling in
anything from src.config or src.database here would drag pydantic-settings env reads into
workflow replay.
"""

from enum import StrEnum


class DispositionCode(StrEnum):
    """All 46 codes from spec §24, verbatim, in spec order. Cross-checked 1:1 against
    tests/fixtures/spec_disposition_codes.txt by tests/unit/test_disposition_action_enums.py
    so an accidental deletion is caught mechanically, not by review."""

    SUCCESS_STATUS_DELIVERED = "SUCCESS_STATUS_DELIVERED"
    SUCCESS_STATUS_AND_QUERY_RESOLVED = "SUCCESS_STATUS_AND_QUERY_RESOLVED"
    SUCCESS_ACTION_CREATED = "SUCCESS_ACTION_CREATED"
    SUCCESS_COMPLAINT_REGISTERED = "SUCCESS_COMPLAINT_REGISTERED"
    SUCCESS_HUMAN_TRANSFER = "SUCCESS_HUMAN_TRANSFER"
    CALLBACK_REQUESTED = "CALLBACK_REQUESTED"
    HUMAN_CALLBACK_REQUIRED = "HUMAN_CALLBACK_REQUIRED"
    RIGHT_PARTY_NOT_AVAILABLE = "RIGHT_PARTY_NOT_AVAILABLE"
    WRONG_PARTY = "WRONG_PARTY"
    AUTH_FAILED = "AUTH_FAILED"
    AUTH_REFUSED = "AUTH_REFUSED"
    CUSTOMER_TERMINATED_CALL = "CUSTOMER_TERMINATED_CALL"
    NO_ANSWER = "NO_ANSWER"
    LINE_BUSY = "LINE_BUSY"
    CALL_REJECTED = "CALL_REJECTED"
    VOICEMAIL = "VOICEMAIL"
    NUMBER_UNREACHABLE = "NUMBER_UNREACHABLE"
    INVALID_CONTACT_NUMBER = "INVALID_CONTACT_NUMBER"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    AI_ESCALATED_LOW_CONFIDENCE = "AI_ESCALATED_LOW_CONFIDENCE"
    AUTOMATED_CONTACT_UNSUCCESSFUL = "AUTOMATED_CONTACT_UNSUCCESSFUL"
    SPECIAL_CUSTOMER_CIRCUMSTANCE = "SPECIAL_CUSTOMER_CIRCUMSTANCE"
    CONSENT_REFUSED = "CONSENT_REFUSED"
    COMMUNICATION_SUPPRESSION_REQUESTED = "COMMUNICATION_SUPPRESSION_REQUESTED"
    ACCESSIBILITY_REQUIREMENT_DETECTED = "ACCESSIBILITY_REQUIREMENT_DETECTED"
    MINOR_ANSWERED = "MINOR_ANSWERED"
    DSAR_REQUESTED = "DSAR_REQUESTED"
    ADVERSARIAL_INPUT_DETECTED = "ADVERSARIAL_INPUT_DETECTED"
    SECURITY_POLICY_ESCALATION = "SECURITY_POLICY_ESCALATION"
    INVALID_OR_UNAUTHORIZED_CLI = "INVALID_OR_UNAUTHORIZED_CLI"
    CONCURRENT_CALL_CONFLICT = "CONCURRENT_CALL_CONFLICT"
    SILENT_CALL_TECHNICAL_FAILURE = "SILENT_CALL_TECHNICAL_FAILURE"
    BACKEND_SYSTEM_FAILURE = "BACKEND_SYSTEM_FAILURE"
    DTMF_FALLBACK_ACTIVATED = "DTMF_FALLBACK_ACTIVATED"
    CUSTOMER_VULNERABILITY_INDICATED = "CUSTOMER_VULNERABILITY_INDICATED"
    FRAUD_SUSPECTED = "FRAUD_SUSPECTED"
    CALL_DROPPED_PRE_AUTH = "CALL_DROPPED_PRE_AUTH"
    CALL_DROPPED_POST_AUTH = "CALL_DROPPED_POST_AUTH"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    STT_SERVICE_FAILURE = "STT_SERVICE_FAILURE"
    TTS_SERVICE_FAILURE = "TTS_SERVICE_FAILURE"
    OTP_ATTEMPTS_EXCEEDED = "OTP_ATTEMPTS_EXCEEDED"
    OTP_LOCKED = "OTP_LOCKED"
    HIGH_RISK_NUMBER_CHANGE_DETECTED = "HIGH_RISK_NUMBER_CHANGE_DETECTED"
    COMPLAINT_SLA_AT_RISK = "COMPLAINT_SLA_AT_RISK"
    COMPLAINT_SLA_BREACHED = "COMPLAINT_SLA_BREACHED"


class CallState(StrEnum):
    """Full Master Call State Machine, spec §3's mermaid diagram. Replaces the Phase 0
    placeholder — see .claude/specs/phase-1-backend-spec.md §3.1."""

    CALL_QUEUED = "CALL_QUEUED"
    DIALING = "DIALING"
    NO_ANSWER = "NO_ANSWER"
    VOICEMAIL = "VOICEMAIL"
    HUMAN_ANSWERED = "HUMAN_ANSWERED"
    FAILED = "FAILED"
    INTRODUCTION = "INTRODUCTION"
    RIGHT_PARTY_CHECK = "RIGHT_PARTY_CHECK"
    WRONG_PARTY = "WRONG_PARTY"
    CUSTOMER_UNAVAILABLE = "CUSTOMER_UNAVAILABLE"
    AUTHENTICATION = "AUTHENTICATION"
    AUTH_RETRY = "AUTH_RETRY"
    AUTHENTICATED = "AUTHENTICATED"
    AUTH_FAILED = "AUTH_FAILED"
    PURPOSE_DISCLOSURE = "PURPOSE_DISCLOSURE"
    STATUS_DELIVERY = "STATUS_DELIVERY"
    FOLLOW_UP = "FOLLOW_UP"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    COMPLAINT = "COMPLAINT"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    CALLBACK_REQUESTED = "CALLBACK_REQUESTED"
    CALLBACK_SCHEDULE = "CALLBACK_SCHEDULE"
    RESOLVED = "RESOLVED"
    RESOLUTION_SUMMARY = "RESOLUTION_SUMMARY"
    TRANSFER_OR_CALLBACK = "TRANSFER_OR_CALLBACK"
    CLOSE = "CLOSE"


# spec §3.1's global interrupts this phase's CallSessionWorkflow does not yet handle —
# reserved signal names so Phase 2/5 extend the signal surface without renaming anything
# Phase 1 shipped. Not driven by any Phase 1 code path.
FUTURE_GLOBAL_INTERRUPTS: frozenset[str] = frozenset(
    {
        "RECORDING_CONSENT_REFUSED",
        "COMMUNICATION_SUPPRESSION_REQUEST",
        "ACCESSIBILITY_REQUIREMENT_DETECTED",
        "DSAR_OR_PRIVACY_RIGHTS_REQUEST",
        "ADVERSARIAL_INPUT_DETECTED",
        "CUSTOMER_VULNERABILITY_INDICATED",
        "FRAUD_SUSPECTED",
        "LEGAL_SENSITIVITY_DETECTED",
        "SAFETY_OR_SECURITY_ESCALATION",
    }
)

# Bounded TTL for the distributed voice lock — spec §4.1. CallSessionWorkflow's
# execution_timeout; if the workflow (or its worker process) hangs or crashes, Temporal
# force-closes the execution once this elapses, freeing the customer-keyed workflow ID for
# the next attempt with no separate lock table or reconciliation job. See
# .claude/specs/phase-1-backend-spec.md decision 0.2.
MAX_CALL_SESSION_SECONDS = 900

# Phase 3, spec §18/§31's REPEATED_CONTACT signal — a deterministic prior-attempt-count
# check (calls/service.py::count_recent_attempts), not an LLM inference. Two plain
# constants, not a new BaseSettings subclass — CLAUDE.md §2.8's "a domain that genuinely
# needs its own settings" bar isn't met by two values. See
# .claude/plans/phase-3-backend-implementation-plan.md Batch 8.
REPEATED_CONTACT_WINDOW_DAYS = 30
REPEATED_CONTACT_THRESHOLD = 3
