"""Imports ONLY `enum` — nothing else. This module runs inside the Temporal workflow
sandbox (see src/calls/workflows.py and tests/integration/test_phase0_e2e.py); pulling in
anything from src.config or src.database here would drag pydantic-settings env reads into
workflow replay.
"""

from enum import StrEnum


class DispositionCode(StrEnum):
    """All 46 codes from spec §24, verbatim, in spec order. Cross-checked 1:1 against
    tests/fixtures/spec_disposition_codes.txt by tests/unit/test_disposition_action_enums.py
    so an accidental deletion is caught mechanically, not by review."""

    SUCCESS_STATUS_DELIVERED = "SUCCESS_STATUS_DELIVERED"
    SUCCESS_STATUS_AND_QUERY_RESOLVED = "SUCCESS_STATUS_AND_QUERY_RESOLVED"
    SUCCESS_ACTION_CREATED = "SUCCESS_ACTION_CREATED"
    SUCCESS_COMPLAINT_REGISTERED = "SUCCESS_COMPLAINT_REGISTERED"
    SUCCESS_HUMAN_TRANSFER = "SUCCESS_HUMAN_TRANSFER"
    CALLBACK_REQUESTED = "CALLBACK_REQUESTED"
    HUMAN_CALLBACK_REQUIRED = "HUMAN_CALLBACK_REQUIRED"
    RIGHT_PARTY_NOT_AVAILABLE = "RIGHT_PARTY_NOT_AVAILABLE"
    WRONG_PARTY = "WRONG_PARTY"
    AUTH_FAILED = "AUTH_FAILED"
    AUTH_REFUSED = "AUTH_REFUSED"
    CUSTOMER_TERMINATED_CALL = "CUSTOMER_TERMINATED_CALL"
    NO_ANSWER = "NO_ANSWER"
    LINE_BUSY = "LINE_BUSY"
    CALL_REJECTED = "CALL_REJECTED"
    VOICEMAIL = "VOICEMAIL"
    NUMBER_UNREACHABLE = "NUMBER_UNREACHABLE"
    INVALID_CONTACT_NUMBER = "INVALID_CONTACT_NUMBER"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    AI_ESCALATED_LOW_CONFIDENCE = "AI_ESCALATED_LOW_CONFIDENCE"
    AUTOMATED_CONTACT_UNSUCCESSFUL = "AUTOMATED_CONTACT_UNSUCCESSFUL"
    SPECIAL_CUSTOMER_CIRCUMSTANCE = "SPECIAL_CUSTOMER_CIRCUMSTANCE"
    CONSENT_REFUSED = "CONSENT_REFUSED"
    COMMUNICATION_SUPPRESSION_REQUESTED = "COMMUNICATION_SUPPRESSION_REQUESTED"
    ACCESSIBILITY_REQUIREMENT_DETECTED = "ACCESSIBILITY_REQUIREMENT_DETECTED"
    MINOR_ANSWERED = "MINOR_ANSWERED"
    DSAR_REQUESTED = "DSAR_REQUESTED"
    ADVERSARIAL_INPUT_DETECTED = "ADVERSARIAL_INPUT_DETECTED"
    SECURITY_POLICY_ESCALATION = "SECURITY_POLICY_ESCALATION"
    INVALID_OR_UNAUTHORIZED_CLI = "INVALID_OR_UNAUTHORIZED_CLI"
    CONCURRENT_CALL_CONFLICT = "CONCURRENT_CALL_CONFLICT"
    SILENT_CALL_TECHNICAL_FAILURE = "SILENT_CALL_TECHNICAL_FAILURE"
    BACKEND_SYSTEM_FAILURE = "BACKEND_SYSTEM_FAILURE"
    DTMF_FALLBACK_ACTIVATED = "DTMF_FALLBACK_ACTIVATED"
    CUSTOMER_VULNERABILITY_INDICATED = "CUSTOMER_VULNERABILITY_INDICATED"
    FRAUD_SUSPECTED = "FRAUD_SUSPECTED"
    CALL_DROPPED_PRE_AUTH = "CALL_DROPPED_PRE_AUTH"
    CALL_DROPPED_POST_AUTH = "CALL_DROPPED_POST_AUTH"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    STT_SERVICE_FAILURE = "STT_SERVICE_FAILURE"
    TTS_SERVICE_FAILURE = "TTS_SERVICE_FAILURE"
    OTP_ATTEMPTS_EXCEEDED = "OTP_ATTEMPTS_EXCEEDED"
    OTP_LOCKED = "OTP_LOCKED"
    HIGH_RISK_NUMBER_CHANGE_DETECTED = "HIGH_RISK_NUMBER_CHANGE_DETECTED"
    COMPLAINT_SLA_AT_RISK = "COMPLAINT_SLA_AT_RISK"
    COMPLAINT_SLA_BREACHED = "COMPLAINT_SLA_BREACHED"


class CallState(StrEnum):
    """Placeholder. Phase 1 replaces this with spec §3's full Master Call State Machine,
    including §3.1's global interrupt states. Names below follow spec §3's mermaid diagram
    so Phase 1 extends this rather than replacing it wholesale."""

    CALL_QUEUED = "CALL_QUEUED"
    DIALING = "DIALING"
    HUMAN_ANSWERED = "HUMAN_ANSWERED"
    INTRODUCTION = "INTRODUCTION"
    RIGHT_PARTY_CHECK = "RIGHT_PARTY_CHECK"
    AUTHENTICATION = "AUTHENTICATION"
    AUTHENTICATED = "AUTHENTICATED"
    PURPOSE_DISCLOSURE = "PURPOSE_DISCLOSURE"
    STATUS_DELIVERY = "STATUS_DELIVERY"
    FOLLOW_UP = "FOLLOW_UP"
    RESOLUTION_SUMMARY = "RESOLUTION_SUMMARY"
    CLOSE = "CLOSE"
