// Mirrors backend/src/calls/constants.py::DispositionCode verbatim — do not reorder or
// abbreviate; DispositionBadge and any future disposition filter depend on exact string match.
export const DISPOSITION_CODES = [
  "SUCCESS_STATUS_DELIVERED", "SUCCESS_STATUS_AND_QUERY_RESOLVED", "SUCCESS_ACTION_CREATED",
  "SUCCESS_COMPLAINT_REGISTERED", "SUCCESS_HUMAN_TRANSFER", "CALLBACK_REQUESTED",
  "HUMAN_CALLBACK_REQUIRED", "RIGHT_PARTY_NOT_AVAILABLE", "WRONG_PARTY", "AUTH_FAILED",
  "AUTH_REFUSED", "CUSTOMER_TERMINATED_CALL", "NO_ANSWER", "LINE_BUSY", "CALL_REJECTED",
  "VOICEMAIL", "NUMBER_UNREACHABLE", "INVALID_CONTACT_NUMBER", "NETWORK_FAILURE",
  "AI_ESCALATED_LOW_CONFIDENCE", "AUTOMATED_CONTACT_UNSUCCESSFUL",
  "SPECIAL_CUSTOMER_CIRCUMSTANCE", "CONSENT_REFUSED", "COMMUNICATION_SUPPRESSION_REQUESTED",
  "ACCESSIBILITY_REQUIREMENT_DETECTED", "MINOR_ANSWERED", "DSAR_REQUESTED",
  "ADVERSARIAL_INPUT_DETECTED", "SECURITY_POLICY_ESCALATION", "INVALID_OR_UNAUTHORIZED_CLI",
  "CONCURRENT_CALL_CONFLICT", "SILENT_CALL_TECHNICAL_FAILURE", "BACKEND_SYSTEM_FAILURE",
  "DTMF_FALLBACK_ACTIVATED", "CUSTOMER_VULNERABILITY_INDICATED", "FRAUD_SUSPECTED",
  "CALL_DROPPED_PRE_AUTH", "CALL_DROPPED_POST_AUTH", "LLM_TIMEOUT", "STT_SERVICE_FAILURE",
  "TTS_SERVICE_FAILURE", "OTP_ATTEMPTS_EXCEEDED", "OTP_LOCKED",
  "HIGH_RISK_NUMBER_CHANGE_DETECTED", "COMPLAINT_SLA_AT_RISK", "COMPLAINT_SLA_BREACHED",
];

// Mirrors backend/src/actions/constants.py::ActionCode verbatim.
export const ACTION_CODES = [
  "CALLBACK_SCHEDULED", "CLAIM_DELAY_ESCALATION", "DOCUMENT_STATUS_DISPUTE",
  "DOCUMENT_SUBMISSION_LINK_REQUEST", "CLAIM_REVIEW_REQUEST", "COMPLAINT_CREATED",
  "HUMAN_CALLBACK_CREATED", "CUSTOMER_CONTACT_DETAILS_REVIEW", "GARAGE_CONTACT_REQUEST",
  "CLAIMS_TEAM_QUERY", "SPECIAL_CIRCUMSTANCE_REVIEW", "COMMUNICATION_SUPPRESSION",
  "DSAR_REQUEST_CREATED", "ACCESSIBLE_CHANNEL_REQUEST", "SECURITY_REVIEW_REQUEST",
  "VULNERABLE_CUSTOMER_SUPPORT_REQUEST", "FRAUD_SIU_REVIEW_REQUEST",
  "EVIDENCE_PRESERVATION_REQUEST", "TECHNICAL_RECOVERY_FOLLOWUP",
  "BACKEND_DATA_VERIFICATION_REQUEST", "COMPLAINT_SLA_ESCALATION",
];

export const VERIFICATION_LEVELS = ["L0", "L1", "L2"];

// Client-side courtesy allow-list only — backend field is an unconstrained str
// (StartCallInput.simulated_answer_result). See phase-1-frontend-spec.md decision 0.7.
export const CALL_ANSWER_RESULTS = ["HUMAN_ANSWERED", "NO_ANSWER", "VOICEMAIL", "FAILED"];

// Client-side courtesy allow-list only — backend fields are unconstrained str
// (ComplaintCreate.severity / .preferred_contact_method). See spec decision 0.8.
export const COMPLAINT_SEVERITIES = ["LOW", "MEDIUM", "HIGH"];
export const COMPLAINT_CONTACT_METHODS = ["PHONE", "EMAIL", "SMS"];
