"""initial schema

Revision ID: 925fc7dbff74
Revises: 
Create Date: 2026-08-27 14:38:11.606235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '925fc7dbff74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('policy_rule', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_event_pkey'))
    )
    op.create_index(op.f('audit_event_call_id_idx'), 'audit_event', ['call_id'], unique=False)
    op.create_index(op.f('audit_event_correlation_id_idx'), 'audit_event', ['correlation_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('national_id_last4', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_pkey'))
    )
    op.create_index(op.f('customer_phone_e164_idx'), 'customer', ['phone_e164'], unique=False)
    op.create_table('idempotency_record',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('operation_name', sa.String(), nullable=False),
    sa.Column('request_fingerprint', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key', name=op.f('idempotency_record_pkey'))
    )
    op.create_index(op.f('idempotency_record_correlation_id_idx'), 'idempotency_record', ['correlation_id'], unique=False)
    op.create_table('repair_garage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_garage_pkey'))
    )
    op.create_table('motor_policy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('vehicle_plate', sa.String(), nullable=False),
    sa.Column('vehicle_make_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('motor_policy_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('motor_policy_pkey'))
    )
    op.create_index(op.f('motor_policy_customer_id_idx'), 'motor_policy', ['customer_id'], unique=False)
    op.create_index(op.f('motor_policy_policy_number_idx'), 'motor_policy', ['policy_number'], unique=False)
    op.create_table('motor_claim',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('garage_id', sa.String(), nullable=True),
    sa.Column('claim_stage', sa.Enum('CLAIM_REGISTERED', 'DOCUMENTS_PENDING', 'DOCUMENTS_RECEIVED', 'SURVEYOR_ASSIGNED', 'INSPECTION_SCHEDULED', 'ASSESSMENT_COMPLETED', 'REPAIR_APPROVAL_PENDING', 'REPAIR_AUTHORIZED', 'VEHICLE_RECEIVED_AT_GARAGE', 'REPAIR_IN_PROGRESS', 'ADDITIONAL_APPROVAL_REQUIRED', 'REPAIR_COMPLETED', 'SETTLEMENT_APPROVED', 'PAYMENT_INITIATED', 'CLAIM_CLOSED', 'CLAIM_DELAYED', 'CLAIM_DECLINED', 'ADDITIONAL_INFORMATION_REQUIRED', name='claim_stage', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('current_owner', sa.String(), nullable=True),
    sa.Column('status_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_expected_event', sa.String(), nullable=True),
    sa.Column('expected_by', sa.DateTime(), nullable=True),
    sa.Column('customer_action_required', sa.Boolean(), nullable=False),
    sa.Column('customer_action_code', sa.String(), nullable=True),
    sa.Column('delay_flag', sa.Boolean(), nullable=False),
    sa.Column('approved_customer_message_key', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('settlement_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('motor_claim_customer_id_fkey')),
    sa.ForeignKeyConstraint(['garage_id'], ['repair_garage.id'], name=op.f('motor_claim_garage_id_fkey')),
    sa.ForeignKeyConstraint(['policy_id'], ['motor_policy.id'], name=op.f('motor_claim_policy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('motor_claim_pkey'))
    )
    op.create_index(op.f('motor_claim_customer_id_idx'), 'motor_claim', ['customer_id'], unique=False)
    op.create_index(op.f('motor_claim_policy_id_idx'), 'motor_claim', ['policy_id'], unique=False)
    op.create_table('claim_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('claim_document_claim_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_document_pkey'))
    )
    op.create_index(op.f('claim_document_claim_id_idx'), 'claim_document', ['claim_id'], unique=False)
    op.create_table('claim_party',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('claim_party_claim_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_party_pkey'))
    )
    op.create_index(op.f('claim_party_claim_id_idx'), 'claim_party', ['claim_id'], unique=False)
    op.create_table('claim_status_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('from_stage', sa.Enum('CLAIM_REGISTERED', 'DOCUMENTS_PENDING', 'DOCUMENTS_RECEIVED', 'SURVEYOR_ASSIGNED', 'INSPECTION_SCHEDULED', 'ASSESSMENT_COMPLETED', 'REPAIR_APPROVAL_PENDING', 'REPAIR_AUTHORIZED', 'VEHICLE_RECEIVED_AT_GARAGE', 'REPAIR_IN_PROGRESS', 'ADDITIONAL_APPROVAL_REQUIRED', 'REPAIR_COMPLETED', 'SETTLEMENT_APPROVED', 'PAYMENT_INITIATED', 'CLAIM_CLOSED', 'CLAIM_DELAYED', 'CLAIM_DECLINED', 'ADDITIONAL_INFORMATION_REQUIRED', name='claim_stage_from', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('to_stage', sa.Enum('CLAIM_REGISTERED', 'DOCUMENTS_PENDING', 'DOCUMENTS_RECEIVED', 'SURVEYOR_ASSIGNED', 'INSPECTION_SCHEDULED', 'ASSESSMENT_COMPLETED', 'REPAIR_APPROVAL_PENDING', 'REPAIR_AUTHORIZED', 'VEHICLE_RECEIVED_AT_GARAGE', 'REPAIR_IN_PROGRESS', 'ADDITIONAL_APPROVAL_REQUIRED', 'REPAIR_COMPLETED', 'SETTLEMENT_APPROVED', 'PAYMENT_INITIATED', 'CLAIM_CLOSED', 'CLAIM_DELAYED', 'CLAIM_DECLINED', 'ADDITIONAL_INFORMATION_REQUIRED', name='claim_stage_to', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('claim_status_event_claim_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_status_event_pkey'))
    )
    op.create_index(op.f('claim_status_event_claim_id_idx'), 'claim_status_event', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('claim_status_event_claim_id_idx'), table_name='claim_status_event')
    op.drop_table('claim_status_event')
    op.drop_index(op.f('claim_party_claim_id_idx'), table_name='claim_party')
    op.drop_table('claim_party')
    op.drop_index(op.f('claim_document_claim_id_idx'), table_name='claim_document')
    op.drop_table('claim_document')
    op.drop_index(op.f('motor_claim_policy_id_idx'), table_name='motor_claim')
    op.drop_index(op.f('motor_claim_customer_id_idx'), table_name='motor_claim')
    op.drop_table('motor_claim')
    op.drop_index(op.f('motor_policy_policy_number_idx'), table_name='motor_policy')
    op.drop_index(op.f('motor_policy_customer_id_idx'), table_name='motor_policy')
    op.drop_table('motor_policy')
    op.drop_table('repair_garage')
    op.drop_index(op.f('idempotency_record_correlation_id_idx'), table_name='idempotency_record')
    op.drop_table('idempotency_record')
    op.drop_index(op.f('customer_phone_e164_idx'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('audit_event_correlation_id_idx'), table_name='audit_event')
    op.drop_index(op.f('audit_event_call_id_idx'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
