"""audit event insert only grants

Revision ID: 01be4bb9bd49
Revises: 925fc7dbff74
Create Date: 2026-08-27 14:38:29.002085

Hand-written, deliberately its own revision (not folded into the autogenerated initial
schema) so the audit-immutability guarantee is a single greppable, independently
reviewable file — `git log -- migrations/versions/*insert_only*` — rather than a few lines
buried in a 150-line autogenerated migration. This is the database layer of the
three-layer enforcement described in src/audit/models.py's module docstring.

TRUNCATE is revoked alongside UPDATE/DELETE — a plain `REVOKE UPDATE, DELETE` leaves a
DELETE-equivalent hole open. Test teardown for audit_event must therefore use the
migrator role, not the app role — see tests/conftest.py's `admin_engine` fixture, which is
itself a live demonstration that this control works.

The `IF EXISTS` guard makes this a no-op on a single-role database (e.g. a developer who
skipped scripts/db/00-init-roles.sql), so that developer gets a working schema rather than
a crashed migration — while the CI/compose path, which always provisions the two roles,
always applies the revoke.
"""

import os
import re
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01be4bb9bd49'
down_revision: Union[str, Sequence[str], None] = '925fc7dbff74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_NAME_PATTERN = re.compile(r"^[a-z_][a-z0-9_]{0,62}$")


def _app_role() -> str:
    role = os.environ.get("APP_DB_ROLE", "callagent_app")
    # This value is interpolated into raw SQL below — validated here, at the one place
    # every consumer of it reads it, as the injection guard. Mirrors the same validator
    # on src.config.Config.APP_DB_ROLE.
    if not _ROLE_NAME_PATTERN.fullmatch(role):
        raise ValueError(f"unsafe Postgres role name: {role!r}")
    return role


def upgrade() -> None:
    role = _app_role()
    op.execute(f"""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
            REVOKE UPDATE, DELETE, TRUNCATE ON TABLE audit_event FROM "{role}";
          END IF;
        END $$;
    """)


def downgrade() -> None:
    role = _app_role()
    op.execute(f"""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
            GRANT UPDATE, DELETE, TRUNCATE ON TABLE audit_event TO "{role}";
          END IF;
        END $$;
    """)
