"""Phase 1 batch 2 — call_attempt, call_session, verification_attempt, otp_challenge,
claim_action, escalation, callback, complaint, complaint_sla_event.

Revision ID: 7fa61b4aba36
Revises: 5e9b1b7ed905
Create Date: 2026-08-27 17:14:51.596075

Hand-reviewed per CLAUDE.md §2.5: same autogenerate false positive on the claim_stage
CHECK constraints as the previous migration — see its docstring. Removed here too; this
migration touches only the nine new tables above.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fa61b4aba36'
down_revision: Union[str, Sequence[str], None] = '5e9b1b7ed905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('escalation_pkey'))
    )
    op.create_index(op.f('escalation_call_id_idx'), 'escalation', ['call_id'], unique=False)
    op.create_table('callback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('callback_window_start', sa.DateTime(), nullable=False),
    sa.Column('callback_window_end', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('callback_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('callback_pkey'))
    )
    op.create_index(op.f('callback_customer_id_idx'), 'callback', ['customer_id'], unique=False)
    op.create_table('claim_action',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('source_call_id', sa.String(), nullable=True),
    sa.Column('action_code', sa.Enum('CALLBACK_SCHEDULED', 'CLAIM_DELAY_ESCALATION', 'DOCUMENT_STATUS_DISPUTE', 'DOCUMENT_SUBMISSION_LINK_REQUEST', 'CLAIM_REVIEW_REQUEST', 'COMPLAINT_CREATED', 'HUMAN_CALLBACK_CREATED', 'CUSTOMER_CONTACT_DETAILS_REVIEW', 'GARAGE_CONTACT_REQUEST', 'CLAIMS_TEAM_QUERY', 'SPECIAL_CIRCUMSTANCE_REVIEW', 'COMMUNICATION_SUPPRESSION', 'DSAR_REQUEST_CREATED', 'ACCESSIBLE_CHANNEL_REQUEST', 'SECURITY_REVIEW_REQUEST', 'VULNERABLE_CUSTOMER_SUPPORT_REQUEST', 'FRAUD_SIU_REVIEW_REQUEST', 'EVIDENCE_PRESERVATION_REQUEST', 'TECHNICAL_RECOVERY_FOLLOWUP', 'BACKEND_DATA_VERIFICATION_REQUEST', 'COMPLAINT_SLA_ESCALATION', name='action_code', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('claim_action_claim_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_action_pkey'))
    )
    op.create_index(op.f('claim_action_claim_id_idx'), 'claim_action', ['claim_id'], unique=False)
    op.create_table('complaint',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('source_call_id', sa.String(), nullable=False),
    sa.Column('complaint_category', sa.String(), nullable=False),
    sa.Column('customer_statement_summary', sa.String(), nullable=False),
    sa.Column('customer_expected_resolution', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('preferred_contact_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('acknowledgment_due_at', sa.DateTime(), nullable=False),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=False),
    sa.Column('sla_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('complaint_claim_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('complaint_pkey'))
    )
    op.create_index(op.f('complaint_claim_id_idx'), 'complaint', ['claim_id'], unique=False)
    op.create_table('call_attempt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_job_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('answer_result', sa.String(), nullable=True),
    sa.Column('disposition_code', sa.Enum('SUCCESS_STATUS_DELIVERED', 'SUCCESS_STATUS_AND_QUERY_RESOLVED', 'SUCCESS_ACTION_CREATED', 'SUCCESS_COMPLAINT_REGISTERED', 'SUCCESS_HUMAN_TRANSFER', 'CALLBACK_REQUESTED', 'HUMAN_CALLBACK_REQUIRED', 'RIGHT_PARTY_NOT_AVAILABLE', 'WRONG_PARTY', 'AUTH_FAILED', 'AUTH_REFUSED', 'CUSTOMER_TERMINATED_CALL', 'NO_ANSWER', 'LINE_BUSY', 'CALL_REJECTED', 'VOICEMAIL', 'NUMBER_UNREACHABLE', 'INVALID_CONTACT_NUMBER', 'NETWORK_FAILURE', 'AI_ESCALATED_LOW_CONFIDENCE', 'AUTOMATED_CONTACT_UNSUCCESSFUL', 'SPECIAL_CUSTOMER_CIRCUMSTANCE', 'CONSENT_REFUSED', 'COMMUNICATION_SUPPRESSION_REQUESTED', 'ACCESSIBILITY_REQUIREMENT_DETECTED', 'MINOR_ANSWERED', 'DSAR_REQUESTED', 'ADVERSARIAL_INPUT_DETECTED', 'SECURITY_POLICY_ESCALATION', 'INVALID_OR_UNAUTHORIZED_CLI', 'CONCURRENT_CALL_CONFLICT', 'SILENT_CALL_TECHNICAL_FAILURE', 'BACKEND_SYSTEM_FAILURE', 'DTMF_FALLBACK_ACTIVATED', 'CUSTOMER_VULNERABILITY_INDICATED', 'FRAUD_SUSPECTED', 'CALL_DROPPED_PRE_AUTH', 'CALL_DROPPED_POST_AUTH', 'LLM_TIMEOUT', 'STT_SERVICE_FAILURE', 'TTS_SERVICE_FAILURE', 'OTP_ATTEMPTS_EXCEEDED', 'OTP_LOCKED', 'HIGH_RISK_NUMBER_CHANGE_DETECTED', 'COMPLAINT_SLA_AT_RISK', 'COMPLAINT_SLA_BREACHED', name='disposition_code', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('customer_reached', sa.Boolean(), nullable=False),
    sa.Column('right_party', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_level', sa.String(), nullable=True),
    sa.Column('status_delivered', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('voicemail_detected', sa.Boolean(), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_job_id'], ['call_job.id'], name=op.f('call_attempt_call_job_id_fkey')),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('call_attempt_claim_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('call_attempt_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_attempt_pkey'))
    )
    op.create_index(op.f('call_attempt_call_job_id_idx'), 'call_attempt', ['call_job_id'], unique=False)
    op.create_index(op.f('call_attempt_claim_id_idx'), 'call_attempt', ['claim_id'], unique=False)
    op.create_index(op.f('call_attempt_customer_id_idx'), 'call_attempt', ['customer_id'], unique=False)
    op.create_table('complaint_sla_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('deadline_kind', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.id'], name=op.f('complaint_sla_event_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('complaint_sla_event_pkey'))
    )
    op.create_index(op.f('complaint_sla_event_complaint_id_idx'), 'complaint_sla_event', ['complaint_id'], unique=False)
    op.create_table('call_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_attempt_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('right_party_confirmed', sa.Boolean(), nullable=False),
    sa.Column('verification_level', sa.String(), nullable=False),
    sa.Column('status_already_disclosed', sa.Boolean(), nullable=False),
    sa.Column('pending_action', sa.String(), nullable=True),
    sa.Column('last_committed_event_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempt.id'], name=op.f('call_session_call_attempt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_session_pkey'))
    )
    op.create_index(op.f('call_session_call_attempt_id_idx'), 'call_session', ['call_attempt_id'], unique=True)
    op.create_table('otp_challenge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_session_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_session.id'], name=op.f('otp_challenge_call_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_challenge_pkey'))
    )
    op.create_index(op.f('otp_challenge_call_session_id_idx'), 'otp_challenge', ['call_session_id'], unique=False)
    op.create_table('verification_attempt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_session_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('factor_type', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_session.id'], name=op.f('verification_attempt_call_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_attempt_pkey'))
    )
    op.create_index(op.f('verification_attempt_call_session_id_idx'), 'verification_attempt', ['call_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('verification_attempt_call_session_id_idx'), table_name='verification_attempt')
    op.drop_table('verification_attempt')
    op.drop_index(op.f('otp_challenge_call_session_id_idx'), table_name='otp_challenge')
    op.drop_table('otp_challenge')
    op.drop_index(op.f('call_session_call_attempt_id_idx'), table_name='call_session')
    op.drop_table('call_session')
    op.drop_index(op.f('complaint_sla_event_complaint_id_idx'), table_name='complaint_sla_event')
    op.drop_table('complaint_sla_event')
    op.drop_index(op.f('call_attempt_customer_id_idx'), table_name='call_attempt')
    op.drop_index(op.f('call_attempt_claim_id_idx'), table_name='call_attempt')
    op.drop_index(op.f('call_attempt_call_job_id_idx'), table_name='call_attempt')
    op.drop_table('call_attempt')
    op.drop_index(op.f('complaint_claim_id_idx'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_index(op.f('claim_action_claim_id_idx'), table_name='claim_action')
    op.drop_table('claim_action')
    op.drop_index(op.f('callback_customer_id_idx'), table_name='callback')
    op.drop_table('callback')
    op.drop_index(op.f('escalation_call_id_idx'), table_name='escalation')
    op.drop_table('escalation')
    # ### end Alembic commands ###
