"""Phase 1 batch 1 — customer_contact_preference, customer_auth_factor,
outbound_campaign, telephony_cli_configuration, business_contact_calendar, call_job.

Revision ID: 5e9b1b7ed905
Revises: 01be4bb9bd49
Create Date: 2026-08-27 17:12:26.089983

Hand-reviewed per CLAUDE.md §2.5: autogenerate also proposed dropping and recreating
the three claim_stage CHECK constraints on motor_claim/claim_status_event — a known
Alembic false positive for Enum(native_enum=False) columns (its CHECK-constraint
comparator re-renders the constraint SQL text and doesn't always match it back to the
existing one even when nothing about claims/models.py changed). Those three
drop/create pairs are removed below; this migration touches only the six new tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9b1b7ed905'
down_revision: Union[str, Sequence[str], None] = '01be4bb9bd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_contact_calendar',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('calendar_type', sa.String(), nullable=False),
    sa.Column('contact_allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('business_contact_calendar_pkey'))
    )
    op.create_index(op.f('business_contact_calendar_calendar_date_idx'), 'business_contact_calendar', ['calendar_date'], unique=False)
    op.create_table('outbound_campaign',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('outbound_campaign_pkey'))
    )
    op.create_table('telephony_cli_configuration',
    sa.Column('cli', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('trunk_authorized', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cli', name=op.f('telephony_cli_configuration_pkey'))
    )
    op.create_table('customer_auth_factor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('factor_type', sa.String(), nullable=False),
    sa.Column('factor_value_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('customer_auth_factor_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_auth_factor_pkey'))
    )
    op.create_index(op.f('customer_auth_factor_customer_id_idx'), 'customer_auth_factor', ['customer_id'], unique=False)
    op.create_table('customer_contact_preference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('preferred_contact_window_start', sa.String(), nullable=True),
    sa.Column('preferred_contact_window_end', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('customer_contact_preference_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_contact_preference_pkey'))
    )
    op.create_index(op.f('customer_contact_preference_customer_id_idx'), 'customer_contact_preference', ['customer_id'], unique=True)
    op.create_table('call_job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['outbound_campaign.id'], name=op.f('call_job_campaign_id_fkey')),
    sa.ForeignKeyConstraint(['claim_id'], ['motor_claim.id'], name=op.f('call_job_claim_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('call_job_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_job_pkey'))
    )
    op.create_index(op.f('call_job_campaign_id_idx'), 'call_job', ['campaign_id'], unique=False)
    op.create_index(op.f('call_job_claim_id_idx'), 'call_job', ['claim_id'], unique=False)
    op.create_index(op.f('call_job_customer_id_idx'), 'call_job', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('call_job_customer_id_idx'), table_name='call_job')
    op.drop_index(op.f('call_job_claim_id_idx'), table_name='call_job')
    op.drop_index(op.f('call_job_campaign_id_idx'), table_name='call_job')
    op.drop_table('call_job')
    op.drop_index(op.f('customer_contact_preference_customer_id_idx'), table_name='customer_contact_preference')
    op.drop_table('customer_contact_preference')
    op.drop_index(op.f('customer_auth_factor_customer_id_idx'), table_name='customer_auth_factor')
    op.drop_table('customer_auth_factor')
    op.drop_table('telephony_cli_configuration')
    op.drop_table('outbound_campaign')
    op.drop_index(op.f('business_contact_calendar_calendar_date_idx'), table_name='business_contact_calendar')
    op.drop_table('business_contact_calendar')
    # ### end Alembic commands ###
